version: '3.8'

services:
  app:
    build: .
    container_name: tinyurl
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    networks:
      - tinyurl_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tinyurl_network

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tinyurl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tinyurl_network

volumes:
  postgres-data:

networks:
  tinyurl_network:
    driver: bridge